
{{- $root := . -}}
{{ range $worker_mode := tuple "interface" "passive" }}
{{- with $root -}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-{{ $worker_mode }}
  labels:
{{ include "chart.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chart.name" . }}-{{ $worker_mode }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "chart.name" . }}-{{ $worker_mode }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
    {{ if (default false .Values.oda.use_hostpath) }}
      - name: scratch
        hostPath:
          path: {{ .Values.oda.worker_scratch }}/dda
          type: DirectoryOrCreate
      - name: filelogdir
        hostPath:
          path: {{ .Values.oda.worker_scratch }}/dda-logs
          type: DirectoryOrCreate
      - name: isdc-arc-rev3
        hostPath:
          path: {{ .Values.oda.isdc_mirror }}/arc/rev_3
      - name: ic-collection
        hostPath:
          path: {{ .Values.oda.ic_collection_mirror }}
      - name: isdc-pvphase-nrt-ops
        hostPath:
          path: {{ .Values.oda.isdc_mirror }}/pvphase/nrt/ops
      - name: data-reduced-ddcache
        hostPath:
          path: {{ .Values.oda.ddcache }}
      - name: data-resources
        hostPath:
          path: {{ .Values.oda.resources }}
    {{ else }}
      - name: scratch
        persistentVolumeClaim:
          claimName: dda-{{ $worker_mode }}-scratch
      - name: filelogdir
        persistentVolumeClaim:
          claimName: dda-filelogdir

    {{ if ( default false .Values.oda.mount_isdc ) }}
      - name: isdc-arc-rev3
        nfs:
          server: {{ .Values.isdc.nfs_server }}
          path: {{ .Values.isdc.path_prefix }}/{{ .Values.isdc.paths.rev_3 }}
          readOnly: true
      - name: isdc-pvphase-nrt-ops
        nfs:
          server: {{ .Values.isdc.nfs_server }}
          path: {{ .Values.isdc.path_prefix }}/{{ .Values.isdc.paths.pvphase_nrt_ops }}
          readOnly: true
      - name: ic-collection
        nfs:
          server: {{ .Values.isdc.nfs_server }}
          path: {{ .Values.isdc.path_prefix }}/{{ .Values.isdc.paths.ic_collection }}
          readOnly: true
      - name: data-reduced-ddcache
        nfs:
          server: {{ .Values.isdc.nfs_server }}
          path: {{ .Values.isdc.path_prefix }}/{{ .Values.isdc.paths.data_reduced_ddcache }}
          readOnly: false
      - name: data-resources
        nfs:
          server: {{ .Values.isdc.nfs_server }}
          path: {{ .Values.isdc.path_prefix }}/{{ .Values.isdc.paths.data_resources }}
          readOnly: false
    {{ else }}
      # these will be populated with archive since it is not mounted
      - name: isdc-arc-rev3
        persistentVolumeClaim:
          claimName: isdc-arc-rev3
      - name: isdc-pvphase-nrt-ops
        persistentVolumeClaim:
          claimName: isdc-pvphase-nrt-ops
      - name: ic-collection
        persistentVolumeClaim:
          claimName: ic-collection
    {{ end }}
    {{ end }}
      - name: config-volume 
        configMap:
          name: oda-data-config
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 10
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 10
          {{- if or (default false .Values.oda.use_hostpath) .Values.oda.mount_isdc }} 
          readinessProbe:
            exec:
              command:
              - ls
              - /data/arc/rev_3/aux/adp/2042.001/time_correlation.fits.gz
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 15 
            timeoutSeconds: 30
          {{- end }}    
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: CURRENT_IC
            value: /data/arc/rev_3
          - name: IC_COLLECTION
            value: /data/ic_collection
          - name: INTEGRAL_DATA
            value: /data/arc/rev_3
          - name: REP_BASE_PROD
            value: /data/arc/rev_3
          - name: REP_BASE_PROD_NRT
            value: /data/rep_base_prod_nrt
          - name: ISDC_REF_CAT
            value: /data/arc/rev_3/cat/hec/gnrl_refr_cat_0043.fits[1]
          - name: INTEGRAL_DDCACHE_ROOT
            value: /data/reduced/ddcache
          - name: WORKER_MODE
            value: {{ $worker_mode }}

          - name: DDA_INTERFACE_TOKEN
            valueFrom:
              secretKeyRef:
                name: dda-interface-token
                key: token.txt

          {{ if .Values.dda_disable_async }}
          - name: DDA_DISABLE_ASYNC
            value: "yes"
          {{ else }}
          - name: ODAHUB
            value: "{{ .Values.oda.crux }}"
          - name: DDA_QUEUE
            value: "{{ .Values.oda.crux }}"
          - name: DDA_TOKEN
            valueFrom:
              secretKeyRef:
                name: dda-token
                key: dda-token
          {{ end }}

          - name: DDA_BOOTSTRAP_DATA
          {{ if .Values.dda_bootstrap_data }}
            value: "yes"
          {{ else }}
            value: "no"
          {{ end }}
          
          - name: DDOSA_SCWDATA_DOWNLOAD
          {{ if .Values.ddosa_scwdata_download }}
            value: "yes"
          {{ else }}
            value: "no"
          {{ end }}

          - name: MIMIC_DDA_GIT_CLONE
            value: "yes"

          volumeMounts:
          - mountPath: /scratch
            name: scratch

          - mountPath: /var/log/containers
            name: filelogdir

          - mountPath: /data/ic_collection
            name: ic-collection
          {{- include "archive_mount_options" . | nindent 12 }}

          - mountPath: /data/arc/rev_3
            name: isdc-arc-rev3
          {{- include "archive_mount_options" . | nindent 12 }}

          - mountPath: /data/rep_base_prod
            name: isdc-arc-rev3
          {{- include "archive_mount_options" . | nindent 12 }}

          - mountPath: /isdc/arc/rev_3
            name: isdc-arc-rev3
          {{- include "archive_mount_options" . | nindent 12 }}

          - mountPath: /data/rep_base_prod_nrt
            name: isdc-pvphase-nrt-ops
          {{- include "archive_mount_options" . | nindent 12 }}

          - mountPath: /data/resources
            name: data-resources
          {{- include "archive_mount_options" . | nindent 12 }}

          - mountPath: /data/reduced/ddcache
            name: data-reduced-ddcache

          - name: config-volume
            mountPath: /etc/passwd
            subPath: etc-passwd

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

{{ end }}
{{ end }}
