apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-passive
  labels:
{{ include "chart.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCountPassive }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chart.name" . }}-passive
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "chart.name" . }}-passive
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: scratch
        hostPath:
          path: /scratch/workers/oda/dda
          type: DirectoryOrCreate
      - name: data-reduced-ddcache
        hostPath:
          path: {{ .Values.data.reduced.ddcache }}
      - name: data-resources
        hostPath:
          path: {{ .Values.data.resources }}
      - name: filelogdir
        hostPath:
          path: /scratch/workers/oda/dda-logs
          type: DirectoryOrCreate
      - name: isdc-arc-rev3
        hostPath:
          path: /isdc/arc/rev_3
      - name: isdc-pvphase-nrt-ops
        hostPath:
          path: /isdc/pvphase/nrt/ops
      - name: config-volume 
        configMap:
          name: oda-data-config
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - ls
              - /data/rep_base_prod/ic
                  #              - df
                  #              - /
            failureThreshold: 5
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 30
          readinessProbe:
            exec:
              command:
              - df
              - /
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: WORKER_MODE
            value: passive
          - name: DDA_INTERFACE_TOKEN
            valueFrom:
              secretKeyRef:
                name: dda-interface-token
                key: token.txt
          - name: DDA_QUEUE
            value: "http://in.internal.odahub.io/staging-1-3/dqueue@{{ .Values.oda.ddaQueue }}"
          - name: DQUEUE_DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: dqueue-database-url
                key: url.txt
          - name: CURRENT_IC
            value: /data/rep_base_prod
          - name: INTEGRAL_DATA
            value: /data/rep_base_prod
          - name: REP_BASE_PROD
            value: /data/rep_base_prod
          - name: ISDC_REF_CAT
            value: /data/rep_base_prod/cat/hec/gnrl_refr_cat_0043.fits[1]
          - name: INTEGRAL_DDCACHE_ROOT
            value: /data/reduced/ddcache
          volumeMounts:
          - mountPath: /scratch
            name: scratch
          - mountPath: /var/log/containers
            name: filelogdir
          - mountPath: /data/rep_base_prod
            name: isdc-arc-rev3
            readOnly: true
          - mountPath: /data/rep_base_prod_nrt
            name: isdc-pvphase-nrt-ops
            readOnly: true
          - mountPath: /data/reduced/ddcache
            name: data-reduced-ddcache
          - mountPath: /data/resources
            name: data-resources
          - mountPath: /etc/passwd
            name: config-volume
            subPath: etc-passwd

                #          - name: MINIO_KEY
                #            valueFrom:
                #                secretKeyRef:
                #                  name: minio-key
                #                  key: minio-key.txt
                #          - name: JENA_PASSWORD
                #            valueFrom:
                #                secretKeyRef:
                #                  name: jena-password
                #                  key: jena-password.txt
                #          - name: LOGSTASH_ENTRYPOINT
                #            valueFrom:
                #                secretKeyRef:
                #                  name: logstash-entrypoint
                #  key: logstash-entrypoint.txt
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
