apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-interface
  labels:
{{ include "chart.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chart.name" . }}-interface
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "chart.name" . }}-interface
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
    {{ if (default .Values.use_hostpath false) }}
      - name: scratch
        hostPath:
          path: {{ .Values.oda.worker_scratch }}/dda
          type: DirectoryOrCreate
      - name: filelogdir
        hostPath:
          path: {{ .Values.oda.worker_scratch }}/dda-logs
          type: DirectoryOrCreate
      - name: isdc-arc-rev3
        hostPath:
          path: {{ .Values.oda.isdc_mirror }}/arc/rev_3
      - name: ic-collection
        hostPath:
          path: {{ .Values.oda.ic_collection_mirror }}
      - name: isdc-pvphase-nrt-ops
        hostPath:
          path: {{ .Values.oda.isdc_mirror }}/pvphase/nrt/ops
      - name: data-reduced-ddcache
        hostPath:
          path: {{ .Values.oda.ddcache }}
      - name: data-resources
        hostPath:
          path: {{ .Values.oda.resources }}
    {{ else }}
      - name: scratch
        persistentVolumeClaim:
          claimName: dda-interface-scratch
      - name: filelogdir
        persistentVolumeClaim:
          claimName: dda-filelogdir
      - name: data-reduced-ddcache
        persistentVolumeClaim:
          claimName: data-reduced-ddcache
      - name: data-resources
        persistentVolumeClaim:
          claimName: data-resources

      # these will be populated with archive since it is not mounted
      - name: isdc-arc-rev3
        persistentVolumeClaim:
          claimName: isdc-arc-rev3
      - name: ic-collection
        persistentVolumeClaim:
          claimName: ic-collection
      - name: isdc-pvphase-nrt-ops
        persistentVolumeClaim:
          claimName: isdc-pvphase-nrt-ops
    {{ end }}
      - name: config-volume 
        configMap:
          name: oda-data-config
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 10
            initialDelaySeconds: 300
            periodSeconds: 120
            timeoutSeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 10
          {{ if (default false .Values.use_hostpath) }}
          readinessProbe:
            exec:
              command:
              - ls
              - /data/rep_base_prod/aux/adp/2042.001/time_correlation.fits.gz
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 15 
            timeoutSeconds: 30
          {{ end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: CURRENT_IC
            value: /data/rep_base_prod
          - name: IC_COLLECTION
            value: /data/ic_collection
          - name: INTEGRAL_DATA
            value: /data/rep_base_prod
          - name: REP_BASE_PROD
            value: /data/rep_base_prod
          - name: REP_BASE_PROD_NRT
            value: /data/rep_base_prod_nrt
          - name: ISDC_REF_CAT
            value: /data/rep_base_prod/cat/hec/gnrl_refr_cat_0043.fits[1]
          - name: INTEGRAL_DDCACHE_ROOT
            value: /data/reduced/ddcache
          - name: WORKER_MODE
            value: interface

          - name: DDA_INTERFACE_TOKEN
            valueFrom:
              secretKeyRef:
                name: dda-interface-token
                key: token.txt

          {{ if .Values.dda_disable_async }}
          - name: DDA_DISABLE_ASYNC
            value: "yes"
          {{ else }}
          - name: ODAHUB
            value: "https://crux.staging-1-3.odahub.io@{{ .Values.oda.ddaQueue }}"
          - name: DDA_QUEUE 
            value: "https://crux.staging-1-3.odahub.io@{{ .Values.oda.ddaQueue }}"
          - name: DDA_TOKEN
            valueFrom:
              secretKeyRef:
                name: dda-token
                key: dda-token
          {{ end }}

          - name: DDA_BOOTSTRAP_DATA
          {{ if .Values.dda_bootstrap_data }}
            value: "yes"
          {{ else }}
            value: "no"
          {{ end }}
          
          - name: DDOSA_SCWDATA_DOWNLOAD
          {{ if .Values.ddosa_scwdata_download }}
            value: "yes"
          {{ else }}
            value: "no"
          {{ end }}

          - name: MIMIC_DDA_GIT_CLONE
            value: "yes"

          volumeMounts:
          - mountPath: /scratch
            name: scratch
          - mountPath: /var/log/containers
            name: filelogdir

          - mountPath: /data/ic_collection
            name: ic-collection
          - mountPath: /data/rep_base_prod
            name: isdc-arc-rev3
          {{ if ( default false .Values.archive_readonly ) }}
            readOnly: true
          {{ end }}
          - mountPath: /isdc/arc/rev_3
            name: isdc-arc-rev3
          {{ if ( default false .Values.archive_readonly ) }}
            readOnly: true
          {{ end }}
          - mountPath: /data/rep_base_prod_nrt
            name: isdc-pvphase-nrt-ops
          {{ if ( default false .Values.archive_readonly ) }}
            readOnly: true
          {{ end }}

          - mountPath: /data/resources
            name: data-resources
          - mountPath: /data/reduced/ddcache
            name: data-reduced-ddcache
          - name: config-volume
            mountPath: /etc/passwd
            subPath: etc-passwd

                #          - name: MINIO_KEY
                #            valueFrom:
                #                secretKeyRef:
                #                  name: minio-key
                #                  key: minio-key.txt
                #          - name: JENA_PASSWORD
                #            valueFrom:
                #                secretKeyRef:
                #                  name: jena-password
                #                  key: jena-password.txt
                #          - name: LOGSTASH_ENTRYPOINT
                #            valueFrom:
                #                secretKeyRef:
                #                  name: logstash-entrypoint
                #  key: logstash-entrypoint.txt
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
