{{ if (default false .Values.oda.use_hostpath) }}
{{ else }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dda-interface-scratch
spec:
  storageClassName: {{ .Values.storage_class_rwmany }} 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dda-filelogdir
spec:
  storageClassName: {{ .Values.storage_class_rwmany }} 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi

{{- $root := . -}}
{{ range .Values.allocate_volumes }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
spec:
  {{ if eq (default "ReadWriteMany" .access_mode) "ReadWriteMany" }}
  storageClassName: {{ $root.Values.storage_class_rwmany }} 
  accessModes:
    - ReadWriteMany
  {{ else }}
  storageClassName: {{ $root.Values.storage_class }} 
  accessModes:
    - ReadWriteOnce
  {{ end }}
  resources:
    requests:
      storage: {{ .size }}
{{ end }}


{{ end }}
